version: '3.7'
services:
  demo_db:
    container_name: demo-mysql-db
    image: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: senha1234
      MYSQL_DATABASE: farmacia
      MYSQL_USER: user
      MYSQL_PASSWORD: password